### ISSUE TITLE
nathanchu

### ISSUE THREAD

**Issue by nathanchu** [nathanchu/nathanchu#1]
Ask me about anything here!

**Comment by Ryyn-Sd** [comment]
# [Can you accept my pull request?](https://github.com/nthnchu/nthnchu/pull/2)

**Comment by Ryyn-Sd** [comment]
Hi

**Comment by Ryyn-Sd** [comment]
How come this is an issue

**Comment by Ryyn-Sd** [comment]
#3

**Comment by nthnchu** [comment]
> How come this is an issue

It's the only way on GitHub to have a chat-like area
